codecov:
  token: "9c7a2e27-2ba1-4a4b-8281-426b13615a73"
  require_ci_to_pass: no
  bot: "codecov-io"
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no 