# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, continuousintegration ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run cucumber-test
    - run: node performance_tests/ListPerformance
    - run: node performance_tests/MapPerformance
    - run: node performance_tests/SetPerformance
    - run: npm install codecov -g
    - run: npm install jest -g
    - run: ./node_modules/.bin/jest --coverage
    - run: codecov --token="9c7a2e27-2ba1-4a4b-8281-426b13615a73"
